
modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId="farmersdelight"
version="1.16.5-0.6.0"
displayName="Farmer's Delight"
# updateJSONURL=""
displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, Grimmauld, ConductiveFoam, simibubi, Jozufozu, bagel, Silk, SkySom, Eutro and many others!"
authors="vectorwing"
description="A lightweight farming and cooking expansion for Minecraft!"
itemIcon="farmersdelight:stove"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
